### ISSUE TITLE
Formly-form controls are not rebound if model is changed programmatically

### ISSUE THREAD

**Issue by Krustie101** [formly-js/ng2-formly#229]
There are 2 levels to this issue 

1) When the model of a formly-form changes, the property values of this new model are not transferred to the corresponding angular FormControl 's and consequently not to the input controls.

2) When I change the value of a model property programmatically, this change is not transferred to the corresponding angular FormControl.

**Comment by aitboudad** [comment]
I'll work on this one

**Comment by aitboudad** [comment]
>When the model of a formly-form changes, the property values of this new model are not transferred to the corresponding angular FormControl 's and consequently not to the input controls.

fixed by #238 but please note we will not support the deep change of model (for the reason mentionned in https://github.com/angular/angular/issues/6458#issuecomment-171299977) and also I would suggest to rely on `FormControl` on this part:
```ts
form.get('email').patchValue(value);
```

> When I change the value of a model property programmatically, this change is not transferred to the corresponding angular FormControl.

@Krustie101 not sure I understand, can you give an example ?
