### ISSUE TITLE
Support ngModelAttrs.

### ISSUE THREAD

**Issue by ckniffen** [formly-js/ng2-formly#27]
The ng2 version should support the ngModelAttrs feature.

**Comment by mohammedzamakhan** [comment]
I want to take the opinion of our angular community in this use case.

**Explanation of `ngModelAttrs`**

Basically in **formly**, we convert Javascript/JSON array object alone to create the whole form in angular 2.

So for example we have the array as
```ts
  fields =  [{
      key: 'email',
      type: 'input',
  }];
  user = {};
```

and the html is

```html
<formly-form [model]="user" [fields]="userFields"></formly-form>
```

we convert this into a form with one form `input` element. A demo of the features can be seen on our website's example here https://ng2.angular-formly.com/guides/introductory-example.html

Basically what we are doing is using componentFactoryResolver to render the `FormlyInputComponent` inside `FormlyFormComponent`.

Suppose the input component is 
```ts
@Component({
  selector: 'formly-field-input',
  template: `
    <input [type]="templateOptions.type" [formControl]="formControl" class="form-control" id="{{key}}"
      [placeholder]="templateOptions.placeholder"
      [formlyNgFocus]="templateOptions.focus" [ngClass]="{'form-control-danger': valid}">
    `,
})
export class FormlyFieldInput extends FieldType { }
```

So the tags `<formly-form ...></formly-form>` gets converted to 

```html
<formly-form>
    <formly-field>
         <input type="text" [formControl]="formControl" class="form-control" id="email">
    <formly-field>
</formly-form>
```

Now comes the feature that the issue speaks about `ngModelAttrs`

Basically if the user have fields with `ngModelAttrs` the field object would look like

```ts
fields =  [{
      key: 'email',
      type: 'input',
      ngModelAttrs: {
         myCustomAttribute: {
            attribute: 'myCustomAttr'
         }
      },
     templateOption: {
         myCustomAttribute: 3
     }
  }];
```

this should result in 

```html
<formly-form>
    <formly-field>
         <input myCustomAttr="3" type="text" [formControl]="formControl" class="form-control" id="email" >
    <formly-field>
</formly-form>
```

The detail use case in angular-formly (Angular 1) can be seen here http://docs.angular-formly.com/v6.3.2/docs/ngmodelattrs.

As we cannot add attribute directives dynamically in Angular 2, what could be the best way to handle this kind of behavior to Angular 2 version of formly?

***Thanks in advance***

@vsavkin, @tbosch, @IgorMinar, @alexeagle, @mhevery, @pkozlowski-opensource, @jeffbcross, @kara, @mprobst, @gdi2290, @robwormald, @jelbourn, @PascalPrecht, @mgechev, @jeffwhelpley
(Tagging as many as possible because many of you would be busy in ng-europe, and I don't want to distract you guys during the conference time 😄 )
