### ISSUE TITLE
SingleFocusDispatcher  not exported via index.ts

### ISSUE THREAD

**Issue by stephanjust** [formly-js/ng2-formly#81]
```SingleFocusDispatcher``` is required when creating your own formly templates, but it is not exported in index.ts and therefore has to be manually imported with the full path.

Considering ```FormlyMessage``` I assume the export belongs in core.ts.

**Comment by divyakumarjain** [comment]
Should we have SingleFocusDispatcher in templates? because this will mostly be used by custom templates. But in any case index.ts exports * templates and core so should not matter.

**Comment by mohammedzamakhan** [comment]
My idea was to keep templates separate so that later on it can be removed from this project and added to ng2-formly-bootstrap-templates project instead of this project, so that we can have ng2-formly-foundation-templates, ng2-formly-material-templates etc. Do you still think this should be done in templates.ts? @divyakumarjain

**Comment by divyakumarjain** [comment]
Answer depends on how we want template projects/modules to be structured. Below are few points which drives makes me think that this issue is valid and PR makes sense. I am open to other suggestions so feel free to suggest and we can update the PR.

- New templates implementation will have its own directory structure. If there is any class that these implementation export then the import syntax will be sometime like `import MaterialRadioButtonDirective from "ng2-formly-material-templates"` it will never be `import xyz from "ng2-formly/templates"`. Thus templates sub-directory of ng2-formly will never conflict with templates implementation's templates sub-directory.
 
- Classes like SingleFocusDispatcher will be used and shared across template implementations and will not be part of specific template implementations. Thus should be kept in single module/project and so far ng-formly base is would best place for it. 

- Also worth noting that classes like SingleFocusDispatcher will not be directly used by ng2-formly clients but will only be used by template implementations. Thus client modules interested in using formly can only focus on importing from ng2-formly/core. Similarly template implementations can import from ng2-formly/templates. ( I guess everything for ng2-formly/templates is again exported via  ng2-formly/core which might need some correction at some point of time)

Let me know if this logically makes sense.
